http {
   
    upstream all {
        # CORREÇÃO: Usando Service Discovery (o nome do serviço definido no docker-compose)
        # O orquestrador distribuirá o tráfego para todas as réplicas do 'php-app'
        server php-app:80;
    }

    server {
         listen 4500;
         location / {
              proxy_pass http://all/;
         }
    }

}


events { }