# nginx.conf CORRIGIDO
events { }

http {
    # Define o grupo de servidores de backend (upstream)
    upstream php_backend {
        # Usamos os NOMES dos serviços definidos no docker-compose.yml
        server php1:80; 
        server php2:80;
        server php3:80;
    }

    server {
        # Escuta na porta 4500, conforme mapeado no docker-compose.yml
        listen 4500; 
        
        location / {
            # Direciona todo o tráfego para o grupo 'php_backend'
            proxy_pass http://php_backend; 
        }
    }
<<<<<<< HEAD

}


events { }
=======
}
>>>>>>> 834e4dc (feat: Configuração final do ambiente Docker Compose. Correção do Load Balancing Nginx, inclusão da extensão PHP pgsql e ajuste da sintaxe da query no index.php.)
